# version: '3.9' Não é necessário colocar a versão porém é uma boa pratica.

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
# networks:

# volumes:
